// c_api_bindings.cpp
// Include the generated C API header (generated by tsujikiri -o c_api) to verify
// it compiles as C++ with the original types in scope.
//
// Generate with:
//   tsujikiri -i tests/test_compilation/combined.input.yml -o c_api -O tests/test_compilation/c_api_bindings.h
//
// Then this file just includes it:
#include "combined.hpp"

#ifdef __has_include
#  if __has_include("c_api_bindings.h")
#    include "c_api_bindings.h"
#  endif
#endif
