from typing import Any

def param_pairs(params: list[dict[str, Any]], name_key: str, sep: str, type_key: str, joiner: str) -> str: ...
def camel_to_snake(name: str) -> str: ...
def snake_to_camel(name: str, uppercase_first: bool = True) -> str: ...
def code_at(injections: list[dict[str, Any]], position: str) -> str: ...
