from dataclasses import dataclass, field

@dataclass
class IRCodeInjection:
    position: str
    code: str

@dataclass
class IRParameter:
    name: str
    type_spelling: str
    emit: bool = ...
    rename: str | None = ...
    type_override: str | None = ...
    default_override: str | None = ...
    default_value: str | None = ...
    ownership: str = ...

@dataclass
class IRBase:
    qualified_name: str
    access: str = ...
    emit: bool = ...

@dataclass
class IRMethod:
    name: str
    spelling: str
    qualified_name: str
    return_type: str
    parameters: list[IRParameter] = field(default_factory=list)
    is_static: bool = ...
    is_const: bool = ...
    is_virtual: bool = ...
    is_pure_virtual: bool = ...
    is_noexcept: bool = ...
    is_varargs: bool = ...
    is_overload: bool = ...
    is_operator: bool = ...
    operator_type: str | None = ...
    is_conversion_operator: bool = ...
    conversion_target_type: str | None = ...
    access: str = ...
    source_file: str | None = ...
    emit: bool = ...
    rename: str | None = ...
    attributes: list[str] = field(default_factory=list)
    return_type_override: str | None = ...
    return_ownership: str = ...
    return_keep_alive: bool = ...
    allow_thread: bool = ...
    wrapper_code: str | None = ...
    doc: str | None = ...
    is_deprecated: bool = ...
    deprecation_message: str | None = ...
    code_injections: list[IRCodeInjection] = field(default_factory=list)
    overload_priority: int | None = ...
    exception_policy: str | None = ...
    api_since: str | None = ...
    api_until: str | None = ...

@dataclass
class IRConstructor:
    parameters: list[IRParameter] = field(default_factory=list)
    is_overload: bool = ...
    is_noexcept: bool = ...
    is_explicit: bool = ...
    is_deleted: bool = ...
    is_varargs: bool = ...
    emit: bool = ...
    doc: str | None = ...
    is_deprecated: bool = ...
    deprecation_message: str | None = ...
    attributes: list[str] = field(default_factory=list)
    code_injections: list[IRCodeInjection] = field(default_factory=list)

@dataclass
class IRField:
    name: str
    type_spelling: str
    is_const: bool = ...
    is_static: bool = ...
    emit: bool = ...
    rename: str | None = ...
    read_only: bool = ...
    type_override: str | None = ...
    doc: str | None = ...
    attributes: list[str] = field(default_factory=list)

@dataclass
class IREnumValue:
    name: str
    value: int
    emit: bool = ...
    rename: str | None = ...
    doc: str | None = ...
    attributes: list[str] = field(default_factory=list)

@dataclass
class IREnum:
    name: str
    qualified_name: str
    values: list[IREnumValue] = field(default_factory=list)
    emit: bool = ...
    is_scoped: bool = ...
    is_anonymous: bool = ...
    is_arithmetic: bool = ...
    rename: str | None = ...
    doc: str | None = ...
    is_deprecated: bool = ...
    deprecation_message: str | None = ...
    attributes: list[str] = field(default_factory=list)
    api_since: str | None = ...
    api_until: str | None = ...

@dataclass
class IRProperty:
    name: str
    getter: str
    setter: str | None = ...
    type_spelling: str = ...
    emit: bool = ...
    doc: str | None = ...

@dataclass
class IRUsingDeclaration:
    member_name: str
    base_qualified_name: str
    access: str = ...
    emit: bool = ...

@dataclass
class IRClass:
    name: str
    qualified_name: str
    namespace: str
    bases: list[IRBase] = field(default_factory=list)
    inner_classes: list[IRClass] = field(default_factory=list)
    constructors: list[IRConstructor] = field(default_factory=list)
    methods: list[IRMethod] = field(default_factory=list)
    fields: list[IRField] = field(default_factory=list)
    enums: list[IREnum] = field(default_factory=list)
    properties: list[IRProperty] = field(default_factory=list)
    has_virtual_methods: bool = ...
    is_abstract: bool = ...
    emit: bool = ...
    rename: str | None = ...
    doc: str | None = ...
    variable_name: str = ...
    parent_class: str | None = ...
    source_file: str | None = ...
    attributes: list[str] = field(default_factory=list)
    copyable: bool | None = ...
    movable: bool | None = ...
    force_abstract: bool = ...
    holder_type: str | None = ...
    has_deleted_copy_constructor: bool = ...
    has_deleted_move_constructor: bool = ...
    is_deprecated: bool = ...
    deprecation_message: str | None = ...
    generate_hash: bool = ...
    smart_pointer_kind: str | None = ...
    smart_pointer_managed_type: str | None = ...
    using_declarations: list[IRUsingDeclaration] = field(default_factory=list)
    code_injections: list[IRCodeInjection] = field(default_factory=list)
    api_since: str | None = ...
    api_until: str | None = ...

@dataclass
class IRExceptionRegistration:
    cpp_exception_type: str
    python_exception_name: str
    base_python_exception: str = ...

@dataclass
class IRFunction:
    name: str
    qualified_name: str
    namespace: str
    return_type: str
    parameters: list[IRParameter] = field(default_factory=list)
    is_overload: bool = ...
    is_noexcept: bool = ...
    is_varargs: bool = ...
    is_operator: bool = ...
    operator_type: str | None = ...
    emit: bool = ...
    rename: str | None = ...
    attributes: list[str] = field(default_factory=list)
    return_type_override: str | None = ...
    return_ownership: str = ...
    return_keep_alive: bool = ...
    allow_thread: bool = ...
    wrapper_code: str | None = ...
    doc: str | None = ...
    is_deprecated: bool = ...
    deprecation_message: str | None = ...
    overload_priority: int | None = ...
    exception_policy: str | None = ...
    api_since: str | None = ...
    api_until: str | None = ...

@dataclass
class IRModule:
    name: str
    namespaces: list[str] = field(default_factory=list)
    classes: list[IRClass] = field(default_factory=list)
    functions: list[IRFunction] = field(default_factory=list)
    enums: list[IREnum] = field(default_factory=list)
    class_by_name: dict[str, IRClass] = field(default_factory=dict)
    exception_registrations: list[IRExceptionRegistration] = field(default_factory=list)
    code_injections: list[IRCodeInjection] = field(default_factory=list)

def merge_modules(modules: list[IRModule]) -> IRModule: ...
