from dataclasses import dataclass, field
from pathlib import Path
from tsujikiri.tir import TIRClass as TIRClass, TIRModule as TIRModule
from typing import Any

@dataclass
class CompatibilityReport:
    breaking_changes: list[str] = field(default_factory=list)
    additive_changes: list[str] = field(default_factory=list)
    @property
    def is_compatible(self) -> bool: ...
    @property
    def has_changes(self) -> bool: ...

def compute_manifest(module: TIRModule) -> dict[str, Any]: ...
def save_manifest(manifest: dict[str, Any], path: Path) -> None: ...
def load_manifest(path: Path) -> dict[str, Any]: ...
def is_semver(s: str) -> bool: ...
def bump_semver(version: str, report: CompatibilityReport) -> str: ...
def suggest_version_bump(old_manifest: dict[str, Any], report: CompatibilityReport) -> str | None: ...
def compare_manifests(old: dict[str, Any], new: dict[str, Any]) -> CompatibilityReport: ...
