from dataclasses import dataclass, field
from tsujikiri.ir import (
    IRBase as IRBase,
    IRClass as IRClass,
    IRCodeInjection as IRCodeInjection,
    IRConstructor as IRConstructor,
    IREnum as IREnum,
    IREnumValue as IREnumValue,
    IRExceptionRegistration as IRExceptionRegistration,
    IRField as IRField,
    IRFunction as IRFunction,
    IRMethod as IRMethod,
    IRModule as IRModule,
    IRParameter as IRParameter,
    IRProperty as IRProperty,
    IRUsingDeclaration as IRUsingDeclaration,
)

@dataclass
class TIRParameter(IRParameter):
    origin: IRParameter | None = field(default=None, init=False, repr=False, compare=False)
    emit: bool = ...
    rename: str | None = ...
    type_override: str | None = ...
    default_override: str | None = ...
    ownership: str = ...
    index: int = ...
    @property
    def binding_name(self) -> str: ...

@dataclass
class TIRBase(IRBase):
    origin: IRBase | None = field(default=None, init=False, repr=False, compare=False)
    emit: bool = ...

@dataclass
class TIRMethod(IRMethod):
    origin: IRMethod | None = field(default=None, init=False, repr=False, compare=False)
    emit: bool = ...
    rename: str | None = ...
    return_type_override: str | None = ...
    return_ownership: str = ...
    return_keep_alive: bool = ...
    allow_thread: bool = ...
    wrapper_code: str | None = ...
    doc: str | None = ...
    code_injections: list[IRCodeInjection] = field(default_factory=list)
    overload_priority: int | None = ...
    exception_policy: str | None = ...
    api_since: str | None = ...
    api_until: str | None = ...
    @property
    def binding_name(self) -> str: ...

@dataclass
class TIRConstructor(IRConstructor):
    origin: IRConstructor | None = field(default=None, init=False, repr=False, compare=False)
    emit: bool = ...
    doc: str | None = ...
    code_injections: list[IRCodeInjection] = field(default_factory=list)

@dataclass
class TIRField(IRField):
    origin: IRField | None = field(default=None, init=False, repr=False, compare=False)
    emit: bool = ...
    rename: str | None = ...
    read_only: bool = ...
    type_override: str | None = ...
    doc: str | None = ...
    @property
    def binding_name(self) -> str: ...

@dataclass
class TIREnumValue(IREnumValue):
    origin: IREnumValue | None = field(default=None, init=False, repr=False, compare=False)
    emit: bool = ...
    rename: str | None = ...
    doc: str | None = ...
    @property
    def binding_name(self) -> str: ...

@dataclass
class TIREnum(IREnum):
    origin: IREnum | None = field(default=None, init=False, repr=False, compare=False)
    emit: bool = ...
    rename: str | None = ...
    doc: str | None = ...
    is_arithmetic: bool = ...
    api_since: str | None = ...
    api_until: str | None = ...
    @property
    def binding_name(self) -> str: ...

@dataclass
class TIRUsingDeclaration(IRUsingDeclaration):
    origin: IRUsingDeclaration | None = field(default=None, init=False, repr=False, compare=False)
    emit: bool = ...

@dataclass
class TIRClass(IRClass):
    origin: IRClass | None = field(default=None, init=False, repr=False, compare=False)
    emit: bool = ...
    rename: str | None = ...
    doc: str | None = ...
    copyable: bool | None = ...
    movable: bool | None = ...
    force_abstract: bool = ...
    holder_type: str | None = ...
    generate_hash: bool = ...
    smart_pointer_kind: str | None = ...
    smart_pointer_managed_type: str | None = ...
    properties: list[IRProperty] = field(default_factory=list)
    code_injections: list[IRCodeInjection] = field(default_factory=list)
    api_since: str | None = ...
    api_until: str | None = ...
    @property
    def binding_name(self) -> str: ...

@dataclass
class TIRFunction(IRFunction):
    origin: IRFunction | None = field(default=None, init=False, repr=False, compare=False)
    emit: bool = ...
    rename: str | None = ...
    return_type_override: str | None = ...
    return_ownership: str = ...
    return_keep_alive: bool = ...
    allow_thread: bool = ...
    wrapper_code: str | None = ...
    doc: str | None = ...
    overload_priority: int | None = ...
    exception_policy: str | None = ...
    api_since: str | None = ...
    api_until: str | None = ...
    @property
    def binding_name(self) -> str: ...

@dataclass
class TIRModule(IRModule):
    origin: IRModule | None = field(default=None, init=False, repr=False, compare=False)
    code_injections: list[IRCodeInjection] = field(default_factory=list)
    exception_registrations: list[IRExceptionRegistration] = field(default_factory=list)

def upgrade_parameter(ir: IRParameter, index: int = 0) -> TIRParameter: ...
def upgrade_base(ir: IRBase) -> TIRBase: ...
def upgrade_method(ir: IRMethod) -> TIRMethod: ...
def upgrade_constructor(ir: IRConstructor) -> TIRConstructor: ...
def upgrade_field(ir: IRField) -> TIRField: ...
def upgrade_enum_value(ir: IREnumValue) -> TIREnumValue: ...
def upgrade_enum(ir: IREnum) -> TIREnum: ...
def upgrade_using_declaration(ir: IRUsingDeclaration) -> TIRUsingDeclaration: ...
def upgrade_class(ir: IRClass) -> TIRClass: ...
def upgrade_function(ir: IRFunction) -> TIRFunction: ...
def upgrade_module(ir: IRModule) -> TIRModule: ...
def merge_tir_modules(modules: list[TIRModule]) -> TIRModule: ...
