from pathlib import Path

def list_builtin_formats(extra_dirs: list[Path] | None = None) -> list[str]: ...
def resolve_format_path(name_or_path: str, extra_dirs: list[Path] | None = None) -> Path: ...
