from pathlib import Path
from tsujikiri.configurations import OutputConfig as OutputConfig

def list_builtin_formats(extra_dirs: list[Path] | None = None) -> list[str]: ...
def resolve_format_path(name_or_path: str, extra_dirs: list[Path] | None = None) -> Path: ...
def apply_format_inheritance(config: OutputConfig, extra_dirs: list[Path] | None = None, _seen: set[str] | None = None) -> OutputConfig: ...
